[[redirects]]
  from = "https://www.griffenedge.me/*"
  to = "https://www.griffenedge.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://griffenedge.me/*"
  to = "https://www.griffenedge.com/:splat"
  status = 301
  force = true
